### PR TITLE
TGR-36: Package update and cleanup

### PR DESCRIPTION
**Pull request by EdwinGuzman**
Node fixes for [TGR-36](https://newyorkpubliclibrary.atlassian.net/browse/TGR-36). This adds on top of the existing PR #106 and resolves the 10 dependabot package issues.

Screenshot 2024-07-22 at 1 57 44 PM

### Add

- Adds the following `npm` packages:
  `babel/preset-typescript`, `babel-jest`

### Update

- Upgrade to Node 20.
- Uses `ts-jest` over `esbuild-jest`.
- Updates the Reservoir DS to `3.1.7` and removes unnecessary stylesheet.
- Updates the following `npm` packages:
  `@nypl/design-system-react-components`, `@parcel/transformer-sass`, `@testing-library/jest-dom`, `@testing-library/react`, `@types/jest`, `@types/js-cookie`, `@types/node`, `@types/react`, `@types/react-dom`, `@types/react-test-renderer`, `@typescript-eslint/eslint-plugin`, `@typescript-eslint/parser`, `esbuild`,  `eslint`, `eslint-config-prettier`, `eslint-plugin-import`, `eslint-plugin-jsx-a11y`, `eslint-plugin-prettier`, `eslint-plugin-react`, `eslint-plugin-react-hooks`, `husky`, `jest`, `jest-config`, `jest-environment-jsdom`, `js-cookie`, `lint-staged`, `os-browserify`, `parcel`, `path-browserify`, `process`, `react`, `react-dom`, `react-error-boundary`, `react-test-renderer`, `ts-jest`, `ts-node`

### Remove

- Removes the following `npm` packages:
  `esbuild-jest`

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
Note: the vercel deployment works but there's a parcel caching issue. This is actually good because we should not deploy this to Vercel at the moment.

**Comment by EdwinGuzman** [comment]
@keithbauer as far as I know or can tell, this front-end is no longer used in https://github.com/NYPL-Simplified/library_registry/. It also looks like the deployment strategy has changed and the UI runs as a standalone app. What I don't know is what the status of `library_registry` is and how it's deployed. Would you happen to know?

**Comment by keithbauer** [comment]
Those are some good questions. I haven't done much work with `library_registry`, but I believe it's still in use by NYPL alongside the Circulation Manager. From what I can tell the `library_registry` is deployed through bamboo though it has been a while since the last deploy. I believe this front-end is still in use and is in the registry's [package.json](https://github.com/NYPL-Simplified/library_registry/blob/develop/package.json#L13), the [Dockerfile](https://github.com/NYPL-Simplified/library_registry/blob/develop/Dockerfile#L166) copies it in and installs.

**Review by keithbauer — APPROVED** [review]

**Comment by EdwinGuzman** [comment]
Right, the previous release is not pointed to in the library registry repo. At some point it seems like the backend and frontend were separated. We'll have to ask for more docs or clarification. It might make any updates easier on the backend if the reference can be removed entirely.

**Review by danamansana — APPROVED** [review]
Looks great, love the 0 vulnerabilities

**Pull request merged**
