### PR TITLE
Use new button styles

### PR DESCRIPTION
**Pull request by adriana-alter**
Goes with https://github.com/NYPL-Simplified/reusable-components/pull/16

Changes:

1) Left-aligned clear search button
Screen Shot 2019-05-17 at 11 09 53 AM

2) Styled log-out button (it looks almost exactly the same as before; the stylesheet is just simpler)
Screen Shot 2019-05-17 at 11 10 32 AM

3) Fixed the issue with the tabs 
-- Before:
Screen Shot 2019-05-17 at 11 11 50 AM
-- After:
Screen Shot 2019-05-17 at 11 12 09 AM

4) Styled the Validate Email and Log In buttons (they look EXACTLY the same as before; the style rules just live in ReusableComponents now).

### CODE REVIEW

**Comment by EdwinGuzman** [comment]
`npm link`-ing the reusable components repo doesn't work so I can't see any updated styles. I think it'll be easier to build if there are fewer classes you have to pass into a component instead of one class per one rule.

**Comment by adriana-alter** [comment]
@EdwinGuzman Try `npm link`-ing it again, and maybe it will magically work this time, like it did for circ-web...?  (It's not giving me any trouble...)

**Comment by EdwinGuzman** [comment]
Nope. I see that it's linking and it's working but the changes are not there. I can show you.

**Comment by adriana-alter** [comment]
I just tried and it wouldn't work for me either (weird!!), but running `npm link` in the ReusableComponents repo in addition to linking from this repo fixed it.  Are you getting error messages or something?

**Comment by EdwinGuzman** [comment]
No errors, just the styling doesn't work. Yes, I did try `npm link`. I will wait until the new component version is published.

**Comment by EdwinGuzman** [comment]
Okay, works now. Just update to 1.3.7 and commit the necessary files.

**Pull request merged**
